# Generated by Aether
# Path: src/components/audit_trail_writer.py
# Purpose: Persist anomaly handling actions and review decisions to the audit trail
# Source: expected_targets

"""Fallback component scaffold for AuditTrailWriter."""

import json
import os
from pathlib import Path


DEFAULT_AUDIT_TRAIL_PATH = Path(__file__).resolve().parents[2] / ".runtime" / "audit_trail.jsonl"


class AuditTrailWriter:
    """Persist anomaly handling actions and review decisions to the audit trail"""

    def __init__(self) -> None:
        configured_path = os.environ.get("DEFIANT_SKY_AUDIT_TRAIL_PATH")
        self.storage_path = Path(configured_path) if configured_path else DEFAULT_AUDIT_TRAIL_PATH

    def write_audit_event(self, audit_event: dict) -> dict:
        """Append a deterministic audit event to local storage."""
        self.storage_path.parent.mkdir(parents=True, exist_ok=True)
        with self.storage_path.open("a", encoding="utf-8") as handle:
            handle.write(json.dumps(audit_event, sort_keys=True) + "\n")
        return {
            "written": True,
            "anomaly_id": str(audit_event.get("anomaly_id", "")),
            "event_type": str(audit_event.get("event_type", "")),
        }
