# Generated by Aether
# Path: src/components/review_queue_manager.py
# Purpose: Queue anomalies for operator review and track review state
# Source: expected_targets

"""Fallback component scaffold for ReviewQueueManager."""

import json
import os
from pathlib import Path


DEFAULT_REVIEW_QUEUE_PATH = Path(__file__).resolve().parents[2] / ".runtime" / "review_queue.json"


class ReviewQueueManager:
    """Queue anomalies for operator review and track review state"""

    def __init__(self) -> None:
        configured_path = os.environ.get("DEFIANT_SKY_REVIEW_QUEUE_PATH")
        self.storage_path = Path(configured_path) if configured_path else DEFAULT_REVIEW_QUEUE_PATH

    def _load_records(self) -> dict[str, dict]:
        if not self.storage_path.exists():
            return {}
        return json.loads(self.storage_path.read_text(encoding="utf-8"))

    def _write_records(self, records: dict[str, dict]) -> None:
        self.storage_path.parent.mkdir(parents=True, exist_ok=True)
        self.storage_path.write_text(
            json.dumps(records, indent=2, sort_keys=True),
            encoding="utf-8",
        )

    def submit_for_review(self, anomaly_record: dict) -> dict:
        """Queue an anomaly record for operator review."""
        anomaly_id = str(anomaly_record.get("anomaly_id", ""))
        records = self._load_records()
        records[anomaly_id] = {
            "anomaly_id": anomaly_id,
            "queued": True,
            "status": str(anomaly_record.get("status", "pending")),
            "record": dict(anomaly_record),
        }
        self._write_records(records)
        return {
            "anomaly_id": anomaly_id,
            "queued": True,
            "status": records[anomaly_id]["status"],
        }

    def update_review_status(self, anomaly_id: str, status: str) -> dict:
        """Update the review status for an anomaly record."""
        records = self._load_records()
        existing = records.get(
            anomaly_id,
            {
                "anomaly_id": anomaly_id,
                "queued": False,
                "record": {
                    "anomaly_id": anomaly_id,
                },
            },
        )
        existing["status"] = status
        existing["record"]["status"] = status
        records[anomaly_id] = existing
        self._write_records(records)
        return {
            "anomaly_id": anomaly_id,
            "status": status,
        }
