# Generated by Aether
# Path: models/approvalartifact.py
# Purpose: Data model for ApprovalArtifact
# Source: data_model

"""Pydantic model for ApprovalArtifact."""

from __future__ import annotations

from pydantic import BaseModel

class ApprovalArtifact(BaseModel):
    """Implementation-ready DGCE model for ApprovalArtifact."""

    approval_status: str | None = None
    artifact_fingerprint: str | None = None
    section_id: str
    preflight_record: PreflightRecord | None = None
