# Generated by Aether
# Path: models/executiongate.py
# Purpose: Data model for ExecutionGate
# Source: data_model

"""Pydantic model for ExecutionGate."""

from __future__ import annotations

from pydantic import BaseModel

class ExecutionGate(BaseModel):
    """Implementation-ready DGCE model for ExecutionGate."""

    artifact_fingerprint: str | None = None
    gate_status: str
    section_id: str
    alignment_record: AlignmentRecord | None = None
