# Generated by Aether
# Path: models/previewartifact.py
# Purpose: Data model for PreviewArtifact
# Source: data_model

"""Pydantic model for PreviewArtifact."""

from __future__ import annotations

from pydantic import BaseModel

class PreviewArtifact(BaseModel):
    """Implementation-ready DGCE model for PreviewArtifact."""

    artifact_fingerprint: str | None = None
    section_id: str
    approval_artifact: ApprovalArtifact | None = None
    review_artifact: ReviewArtifact | None = None
