# Generated by Aether
# Path: api/alignmentrecordinterface.py
# Purpose: API interface for AlignmentRecordInterface
# Source: api_surface

"""API scaffold for API interface for AlignmentRecordInterface."""

class Alignmentrecordinterface:
    """Defines the api interface for alignmentrecordinterface."""

    pass
