# Generated by Aether
# Path: api/alignmentrecord.py
# Purpose: API interface for AlignmentRecord
# Source: api_surface

"""API scaffold for API interface for AlignmentRecord."""

class Alignmentrecord:
    """Defines the api interface for alignmentrecord."""

    pass
