# Generated by Aether
# Path: api/approvalartifact.py
# Purpose: API interface for ApprovalArtifact
# Source: api_surface

"""API scaffold for API interface for ApprovalArtifact."""

class Approvalartifact:
    """Defines the api interface for approvalartifact."""

    pass
