# Generated by Aether
# Path: api/approvalartifactinterface.py
# Purpose: API interface for ApprovalArtifactInterface
# Source: api_surface

"""API scaffold for API interface for ApprovalArtifactInterface."""

class Approvalartifactinterface:
    """Defines the api interface for approvalartifactinterface."""

    pass
