# Generated by Aether
# Path: api/datamodelservice.py
# Purpose: API interface for DataModelService
# Source: api_surface

"""API scaffold for API interface for DataModelService."""

class Datamodelservice:
    """Defines the api interface for datamodelservice."""

    pass
