# Generated by Aether
# Path: api/description_interface_for_managing_data_model_entities_in_dgce_name_datamodelservice.py
# Purpose: API interface for {'description': 'Interface for managing data model entities in DGCE.', 'name': 'DataModelService'}
# Source: api_surface

"""API scaffold for API interface for {'description': 'Interface for managing data model entities in DGCE.', 'name': 'DataModelService'}."""

class DescriptionInterfaceForManagingDataModelEntitiesInDgceNameDatamodelservice:
    """Defines the api interface for {'description': 'interface for managing data model entities in dgce.', 'name': 'datamodelservice'}."""

    pass
