# Generated by Aether
# Path: api/dgcemodelinterface.py
# Purpose: API interface for DGCEModelInterface
# Source: api_surface

"""API scaffold for API interface for DGCEModelInterface."""

class Dgcemodelinterface:
    """Defines the api interface for dgcemodelinterface."""

    pass
