# Generated by Aether
# Path: api/dgcedatamodel.py
# Purpose: API interface for DGCEDataModel
# Source: api_surface

"""API scaffold for API interface for DGCEDataModel."""

class Dgcedatamodel:
    """Defines the api interface for dgcedatamodel."""

    pass
