# Generated by Aether
# Path: api/name_dgce_version_1_0.py
# Purpose: API interface for {'name': 'DGCE', 'version': '1.0'}
# Source: api_surface

"""API scaffold for API interface for {'name': 'DGCE', 'version': '1.0'}."""

class NameDgceVersion10:
    """Defines the api interface for {'name': 'dgce', 'version': '1.0'}."""

    pass
