# Generated by Aether
# Path: api/preflightrecord.py
# Purpose: API interface for PreflightRecord
# Source: api_surface

"""API scaffold for API interface for PreflightRecord."""

class Preflightrecord:
    """Defines the api interface for preflightrecord."""

    pass
