# Generated by Aether
# Path: api/preflightrecordinterface.py
# Purpose: API interface for PreflightRecordInterface
# Source: api_surface

"""API scaffold for API interface for PreflightRecordInterface."""

class Preflightrecordinterface:
    """Defines the api interface for preflightrecordinterface."""

    pass
