# Generated by Aether
# Path: api/previewartifactinterface.py
# Purpose: API interface for PreviewArtifactInterface
# Source: api_surface

"""API scaffold for API interface for PreviewArtifactInterface."""

class Previewartifactinterface:
    """Defines the api interface for previewartifactinterface."""

    pass
