# Generated by Aether
# Path: api/previewartifact.py
# Purpose: API interface for PreviewArtifact
# Source: api_surface

"""API scaffold for API interface for PreviewArtifact."""

class Previewartifact:
    """Defines the api interface for previewartifact."""

    pass
