# Generated by Aether
# Path: api/sectioninput.py
# Purpose: API interface for SectionInput
# Source: api_surface

"""API scaffold for API interface for SectionInput."""

class Sectioninput:
    """Defines the api interface for sectioninput."""

    pass
