"""Deterministic scaffold writer for DGCE file plans."""

import keyword
import os
import re
from pathlib import Path
from typing import Iterable, List

from aether.dgce.file_plan import FilePlan


def write_file_plan(
    file_plan: FilePlan,
    output_dir: Path,
    *,
    overwrite_paths: Iterable[str] | None = None,
) -> List[str]:
    """Write a DGCE scaffold to disk under an explicit output directory."""
    root = output_dir.resolve()
    root.mkdir(parents=True, exist_ok=True)
    allowed_overwrites = {Path(path).as_posix() for path in (overwrite_paths or [])}

    written_files: list[str] = []
    for file_entry in file_plan.files:
        relative_path = Path(str(file_entry["path"]))
        target_path = (root / relative_path).resolve()
        _ensure_within_output_dir(root, target_path)
        normalized_path = relative_path.as_posix()

        if target_path.exists():
            if normalized_path not in allowed_overwrites:
                raise FileExistsError(f"Target file already exists: {normalized_path}")
            if target_path.is_dir():
                raise IsADirectoryError(f"Target path is a directory: {normalized_path}")

        target_path.parent.mkdir(parents=True, exist_ok=True)
        target_path.write_bytes(render_file_entry_bytes(file_entry))
        written_files.append(normalized_path)

    return written_files


def _ensure_within_output_dir(output_dir: Path, target_path: Path) -> None:
    """Reject any target path that escapes the intended output directory."""
    try:
        target_path.relative_to(output_dir)
    except ValueError as exc:
        raise ValueError(f"Target path escapes output_dir: {target_path}") from exc


def render_file_entry_content(file_entry: dict) -> str:
    """Return deterministic scaffold file content for one file-plan entry."""
    explicit_content = file_entry.get("content")
    if isinstance(explicit_content, str):
        return explicit_content if explicit_content.endswith("\n") else f"{explicit_content}\n"
    path = str(file_entry["path"])
    purpose = str(file_entry["purpose"])
    source = str(file_entry["source"])
    requirements = [
        str(requirement)
        for requirement in file_entry.get("requirements", [])
        if isinstance(requirement, str)
    ]
    relative_path = Path(path)
    header = [
        "# Generated by Aether",
        f"# Path: {path}",
        f"# Purpose: {purpose}",
        f"# Source: {source}",
        "",
    ]

    if source == "expected_targets":
        return _render_expected_target_content(relative_path, purpose, requirements, header)

    if source == "data_model" and relative_path.parts[:1] == ("models",):
        return _render_data_model_content(file_entry, header)

    if source == "api_surface" and relative_path.parts[:1] == ("api",) and isinstance(file_entry.get("interface_schema"), dict):
        return _render_api_surface_content(file_entry, header)

    if source == "system_breakdown" and isinstance(file_entry.get("module_contract"), dict):
        return _render_system_breakdown_content(file_entry, header)

    if relative_path.parts[:1] == ("models",):
        return "\n".join(
            header
            + [
                f'"""Model scaffold for {purpose}."""',
                "",
                f"class {_class_name(relative_path.stem)}:",
                f'    """Represents {purpose.lower()}."""',
                "",
                "    pass",
                "",
            ]
        )

    if relative_path.parts[:1] == ("api",):
        return "\n".join(
            header
            + [
                f'"""API scaffold for {purpose}."""',
                "",
                f"class {_class_name(relative_path.stem)}:",
                f'    """Defines the {purpose.lower()}."""',
                "",
                "    pass",
                "",
            ]
        )

    if relative_path.name == "service.py":
        service_name = _class_name(relative_path.parent.name) + "Service"
        return "\n".join(
            header
            + [
                f'"""Service scaffold for {purpose}."""',
                "",
                f"class {service_name}:",
                f'    """Coordinates {purpose.lower()}."""',
                "",
                "    pass",
                "",
            ]
        )

    if relative_path.name == "models.py":
        model_name = _class_name(relative_path.parent.name) + "Model"
        return "\n".join(
            header
            + [
                f'"""Model container scaffold for {purpose}."""',
                "",
                f"class {model_name}:",
                f'    """Placeholder model for {purpose.lower()}."""',
                "",
                "    pass",
                "",
            ]
        )

    return "\n".join(
        header
        + [
            f'"""Scaffold for {purpose}."""',
            "",
            f"class {_class_name(relative_path.stem)}:",
            f'    """Placeholder for {purpose.lower()}."""',
            "",
            "    pass",
            "",
        ]
    )


def _render_expected_target_content(
    relative_path: Path,
    purpose: str,
    requirements: list[str],
    header: list[str],
) -> str:
    """Render richer first-pass scaffolds for expected-target bootstrap files."""
    normalized_path = relative_path.as_posix()
    if normalized_path.startswith("src/models/") and relative_path.suffix == ".py":
        class_name = _expected_target_class_name(relative_path.stem)
        description = purpose or f"Fallback model scaffold for {class_name}."
        fields = _infer_model_fields(class_name, requirements)
        validate_method = _render_model_validate_method(fields, requirements)
        model_body = _render_model_fields(fields)
        extra_methods = []
        if class_name == "AnomalyRecord" and _requirements_mention_status(requirements):
            extra_methods.extend(
                [
                    "",
                    "    # Allowed status values: pending, approved, rejected",
                    "    def mark_reviewed(self, status: str) -> None:",
                    '        """Update the record status after operator review."""',
                    '        if status not in {"approved", "rejected"}:',
                    '            raise ValueError("status must be approved or rejected")',
                    "        self.status = status",
                ]
            )
        return "\n".join(
            header
            + [
                "from dataclasses import dataclass",
                "",
                f'"""Fallback model scaffold for {class_name}."""',
                "",
                "@dataclass",
                f"class {class_name}:",
                f'    """{description}"""',
                "",
            ]
            + model_body
            + [
                "",
            ]
            + validate_method
            + extra_methods
            + [
                "",
            ]
        )

    if normalized_path.startswith("src/components/") and relative_path.suffix == ".py":
        class_name = _expected_target_class_name(relative_path.stem)
        method_lines = _render_component_method_lines(class_name, purpose, requirements)
        description = purpose or f"Fallback component scaffold for {class_name}."
        return "\n".join(
            header
            + [
                f'"""Fallback component scaffold for {class_name}."""',
                "",
                f"class {class_name}:",
                f'    """{description}"""',
                "",
            ]
            + method_lines
            + [
                "",
            ]
        )

    if normalized_path.startswith("src/api/") and relative_path.suffix == ".py":
        if relative_path.stem == "ingest":
            return "\n".join(
                header
                + [
                    '"""Fallback API scaffold for ingest."""',
                    "",
                    "def ingest_observation(payload: dict) -> dict:",
                    '    """',
                    "    Ingest an observation, normalize it, compute expected state, score deviation,",
                    "    classify anomaly, and return a structured result.",
                    '    """',
                    "",
                    "    # normalize",
                    "    normalized = payload  # placeholder",
                    "",
                    "    # propagate expected state",
                    "    expected_state = {}",
                    "",
                    "    # score deviation",
                    "    deviation_score = 0.0",
                    "",
                    "    # classify anomaly",
                    "    result = {",
                    '        "anomaly_type": "unknown",',
                    '        "confidence": 0.0,',
                    '        "deviation_score": deviation_score,',
                    "    }",
                    "",
                    "    return result",
                    "",
                ]
            )

        if relative_path.stem == "review":
            return "\n".join(
                header
                + [
                    '"""Fallback API scaffold for review."""',
                    "",
                    "def review_anomaly(anomaly_record: dict, status: str) -> dict:",
                    '    """',
                    "    Review an anomaly record, apply the requested review status,",
                    "    and return a structured review result.",
                    '    """',
                    "",
                    '    if status not in {"approved", "rejected"}:',
                    '        raise ValueError("status must be approved or rejected")',
                    "",
                    "    updated_record = dict(anomaly_record)",
                    '    updated_record["status"] = status',
                    "",
                    "    return {",
                    '        "anomaly_id": updated_record.get("anomaly_id", ""),',
                    '        "status": status,',
                    '        "updated_record": updated_record,',
                    "    }",
                    "",
                ]
            )

        function_name = _infer_api_function_name(purpose, relative_path.stem)
        description = purpose or f"Fallback API scaffold for {relative_path.stem}."
        return "\n".join(
            header
            + [
                f'"""Fallback API scaffold for {relative_path.stem}."""',
                "",
                f"def {function_name}(payload: dict) -> dict:",
                f'    """{description}"""',
                "    raise NotImplementedError",
                "",
            ]
        )

    if normalized_path.startswith("tests/") and relative_path.suffix == ".py":
        test_name = _infer_test_name(relative_path.stem)
        return "\n".join(
            header
            + [
                "import pytest",
                "",
                f"def {test_name}() -> None:",
                '    """Placeholder bootstrap test."""',
                "    assert True",
                "",
            ]
        )

    return "\n".join(
        header
        + [
            f'"""Fallback scaffold for {purpose or relative_path.stem}."""',
            "",
            f"class {_expected_target_class_name(relative_path.stem)}:",
            '    """Placeholder bootstrap scaffold."""',
            "",
            "    pass",
            "",
        ]
    )


def _render_system_breakdown_content(file_entry: dict, header: list[str]) -> str:
    """Render a richer deterministic scaffold for structured system-breakdown files."""
    relative_path = Path(str(file_entry["path"]))
    module_contract = file_entry.get("module_contract")
    if not isinstance(module_contract, dict):
        return "\n".join(header + [""])
    if relative_path.name == "service.py":
        return _render_system_breakdown_service_content(file_entry, header, module_contract)
    if relative_path.name == "models.py":
        return _render_system_breakdown_model_content(file_entry, header, module_contract)
    return "\n".join(header + [""])


def _render_system_breakdown_service_content(file_entry: dict, header: list[str], module_contract: dict) -> str:
    """Render a deterministic service scaffold from one normalized module contract."""
    service_name = str(module_contract.get("name") or _class_name(Path(str(file_entry["path"])).parent.name)) + "Service"
    dependencies = tuple(
        str(dependency.get("name"))
        for dependency in module_contract.get("dependencies", [])
        if isinstance(dependency, dict) and isinstance(dependency.get("name"), str)
    )
    outputs = [
        str(port.get("name"))
        for port in module_contract.get("outputs", [])
        if isinstance(port, dict) and isinstance(port.get("name"), str)
    ]
    return "\n".join(
        header
        + [
            f'"""Service scaffold for {file_entry["purpose"]}."""',
            "",
            "from __future__ import annotations",
            "",
            "from typing import Any",
            "",
            f"class {service_name}:",
            f'    """{str(module_contract.get("responsibility", "")).strip() or str(file_entry.get("purpose", ""))}"""',
            "",
            f"    DEPENDENCIES = {dependencies!r}",
            f"    OWNED_PATHS = {tuple(str(path) for path in module_contract.get('owned_paths', []))!r}",
            "",
            "    def run(self, payload: dict[str, Any]) -> dict[str, Any]:",
            '        """Execute one deterministic implementation unit."""',
            "        return {",
        ]
        + [f'            "{_python_attribute_name(name) or name}": None,' for name in outputs]
        + [
            "        }",
            "",
        ]
    )


def _render_system_breakdown_model_content(file_entry: dict, header: list[str], module_contract: dict) -> str:
    """Render deterministic module contract constants for structured model scaffolds."""
    lines = [
        f'"""Model container scaffold for {file_entry["purpose"]}."""',
        "",
        "from __future__ import annotations",
        "",
        f"MODULE_NAME = {module_contract.get('name', '')!r}",
        f"LAYER = {module_contract.get('layer', '')!r}",
        f"RESPONSIBILITY = {str(module_contract.get('responsibility', '')).strip()!r}",
        f"OWNED_PATHS = {tuple(str(path) for path in module_contract.get('owned_paths', []))!r}",
        f"INPUT_PORTS = {_repr_system_breakdown_ports(module_contract.get('inputs', []))}",
        f"OUTPUT_PORTS = {_repr_system_breakdown_ports(module_contract.get('outputs', []))}",
        "",
    ]
    return "\n".join(header + lines)


def _repr_system_breakdown_ports(ports: object) -> str:
    """Return a deterministic repr for normalized input/output port collections."""
    if not isinstance(ports, list):
        return "()"
    normalized_ports = []
    for port in ports:
        if not isinstance(port, dict):
            continue
        normalized_ports.append(
            {
                "artifact_path": port.get("artifact_path"),
                "name": port.get("name"),
                "schema_fields": port.get("schema_fields"),
                "type": port.get("type"),
            }
        )
    return repr(tuple(normalized_ports))


def render_file_entry_bytes(file_entry: dict) -> bytes:
    """Return the exact bytes the scaffold writer will persist for one file-plan entry."""
    return render_file_entry_content(file_entry).replace("\n", os.linesep).encode("utf-8")


def _render_data_model_content(file_entry: dict, header: list[str]) -> str:
    """Render a Pydantic BaseModel from validated DGCE data-model metadata when available."""
    entity_schema = file_entry.get("entity_schema")
    if not isinstance(entity_schema, dict):
        relative_path = Path(str(file_entry["path"]))
        class_name = _fallback_data_model_class_name(relative_path.stem, str(file_entry.get("purpose", "")))
        return "\n".join(
            header
            + [
                f'"""Model scaffold for {file_entry["purpose"]}."""',
                "",
                "from __future__ import annotations",
                "",
                "from typing import Any",
                "",
                "from pydantic import BaseModel",
                "",
                f"class {class_name}(BaseModel):",
                '    """Structured fallback model when entity schema details are unavailable."""',
                "",
                "    raw_payload: dict[str, Any]",
                "",
            ]
        )

    class_name = str(entity_schema.get("name") or _fallback_data_model_class_name(Path(str(file_entry["path"])).stem, str(file_entry.get("purpose", ""))))
    fields = _render_data_model_field_lines(file_entry, class_name, entity_schema)
    requires_any = any("Any" in line for line in fields)
    requires_datetime = any("datetime" in line for line in fields)
    requires_literal = any("Literal[" in line for line in fields)
    imports = [
        f'"""Pydantic model for {class_name}."""',
        "",
        "from __future__ import annotations",
        "",
    ]
    typing_imports: list[str] = []
    if requires_any:
        typing_imports.append("Any")
    if requires_literal:
        typing_imports.append("Literal")
    if typing_imports:
        imports.extend(
            [
                f"from typing import {', '.join(typing_imports)}",
                "",
            ]
        )
    if requires_datetime:
        imports.extend(
            [
                "from datetime import datetime",
                "",
            ]
        )
    imports.extend(
        [
            "from pydantic import BaseModel",
            "",
            f"class {class_name}(BaseModel):",
            f'    """Implementation-ready DGCE model for {class_name}."""',
            "",
        ]
    )
    return "\n".join(header + imports + fields + [""])


def _render_api_surface_content(file_entry: dict, header: list[str]) -> str:
    """Render an implementation-ready service class from validated api-surface metadata when available."""
    interface_schema = file_entry.get("interface_schema")
    if not isinstance(interface_schema, dict):
        relative_path = Path(str(file_entry["path"]))
        class_name = _class_name(relative_path.stem)
        return "\n".join(
            header
            + [
                f'"""API scaffold for {file_entry["purpose"]}."""',
                "",
                f"class {class_name}:",
                '    """Structured fallback API service when interface schema details are unavailable."""',
                "",
                "    pass",
                "",
            ]
        )

    class_name = str(interface_schema.get("name") or _class_name(Path(str(file_entry["path"])).stem))
    methods = interface_schema.get("methods", [])
    schemas = interface_schema.get("schemas", {})
    if isinstance(methods, list) and methods and isinstance(schemas, dict) and any(
        isinstance(method, dict) and isinstance(method.get("response_schema"), str)
        for method in methods
    ):
        body = [
            f'"""Service contract for {class_name}."""',
            "",
            "from __future__ import annotations",
            "",
            "from typing import Any",
            "",
            "from fastapi import APIRouter",
            "from pydantic import BaseModel",
            "",
            "router = APIRouter()",
            "",
        ]
        body.extend(_render_api_surface_schema_models(schemas))
        if body[-1] != "":
            body.append("")
        for index, method in enumerate(methods):
            if not isinstance(method, dict):
                continue
            if index:
                body.append("")
            body.extend(_render_api_surface_endpoint_lines(method, schemas))
        return "\n".join(header + body + [""])

    body = [
        f'"""Service contract for {class_name}."""',
        "",
        "from __future__ import annotations",
        "",
        "from typing import Any",
        "",
        f"class {class_name}:",
        f'    """Implementation-ready DGCE API service for {class_name}."""',
        "",
    ]
    if isinstance(methods, list) and methods:
        for index, method in enumerate(methods):
            if not isinstance(method, dict):
                continue
            if index:
                body.append("")
            body.extend(_render_api_surface_method_lines(method))
    else:
        body.extend(
            [
                "    def handle(self, payload: dict[str, Any]) -> dict[str, Any]:",
                '        """Fallback API handler."""',
                "        return payload",
            ]
        )
    return "\n".join(header + body + [""])


def _class_name(value: str) -> str:
    """Return a deterministic Python class name from a file stem or directory name."""
    return "".join(part.capitalize() for part in value.replace("-", "_").split("_")) or "GeneratedStub"


def _render_data_model_field_lines(file_entry: dict, class_name: str, entity_schema: dict) -> list[str]:
    """Render deterministic typed Pydantic fields plus derived relationship references."""
    known_entity_names = {
        str(name)
        for name in file_entry.get("known_entity_names", [])
        if isinstance(name, str) and name
    }
    rendered: list[str] = []
    seen_attributes: set[str] = set()

    for field in entity_schema.get("fields", []):
        if not isinstance(field, dict):
            continue
        field_name = _python_attribute_name(str(field.get("name", "")))
        if not field_name or field_name in seen_attributes:
            continue
        annotation = _python_type_for_data_model_field(field.get("type"), known_entity_names)
        annotation = _field_annotation_with_enum_values(annotation, field.get("enum_values"))
        required = bool(field.get("required", False))
        rendered.append(_render_pydantic_field_line(field_name, annotation, required))
        seen_attributes.add(field_name)

    for relationship in file_entry.get("entity_relationships", []):
        if not isinstance(relationship, dict):
            continue
        target_entity = str(relationship.get("to_entity", "")).strip()
        if not target_entity or target_entity == class_name:
            continue
        attribute_name = _python_attribute_name(target_entity)
        if not attribute_name or attribute_name in seen_attributes:
            continue
        rendered.append(f"    {attribute_name}: {target_entity} | None = None")
        seen_attributes.add(attribute_name)

    if rendered:
        return rendered

    identity_keys = entity_schema.get("identity_keys", [])
    for identity_key in identity_keys:
        if not isinstance(identity_key, str) or not identity_key.strip():
            continue
        field_name = _python_attribute_name(identity_key)
        if not field_name or field_name in seen_attributes:
            continue
        rendered.append(f"    {field_name}: str")
        seen_attributes.add(field_name)

    if rendered:
        return rendered

    return ["    raw_payload: dict[str, Any]"]


def _render_pydantic_field_line(field_name: str, annotation: str, required: bool) -> str:
    """Render one typed Pydantic field line."""
    if required:
        return f"    {field_name}: {annotation}"
    return f"    {field_name}: {annotation} | None = None"


def _render_api_surface_method_lines(method: dict) -> list[str]:
    """Render one deterministic API service method stub."""
    method_name = str(method.get("name", "handle"))
    input_payload = method.get("input", {})
    output_payload = method.get("output", {})
    error_cases = method.get("error_cases", [])
    signature = _api_surface_method_signature(input_payload)
    response_lines = _api_surface_response_lines(output_payload)
    rendered = [
        f"    def {method_name}(self, {signature}) -> dict[str, Any]:",
        f'        """{str(method.get("method", "GET"))} {str(method.get("path", "/"))}."""',
    ]
    if isinstance(error_cases, list) and error_cases:
        rendered.append(f"        # error_cases: {', '.join(str(case) for case in error_cases)}")
    rendered.extend(response_lines)
    return rendered


def _render_api_surface_schema_models(schemas: dict) -> list[str]:
    """Render deterministic Pydantic schema models for one api-surface file."""
    rendered: list[str] = []
    for schema_name, schema_payload in schemas.items():
        if not isinstance(schema_payload, dict):
            continue
        fields = schema_payload.get("fields", [])
        rendered.append(f"class {schema_name}(BaseModel):")
        schema_fields = _render_api_surface_schema_field_lines(fields)
        rendered.extend(schema_fields or ["    pass"])
        rendered.append("")
    if rendered and rendered[-1] == "":
        rendered.pop()
    return rendered


def _render_api_surface_schema_field_lines(fields: object) -> list[str]:
    """Render deterministic schema field lines in their normalized order."""
    if not isinstance(fields, list):
        return []
    rendered: list[str] = []
    seen_fields: set[str] = set()
    for field in fields:
        if not isinstance(field, dict):
            continue
        field_name = _python_attribute_name(str(field.get("name", "")))
        if not field_name or field_name in seen_fields:
            continue
        annotation = _python_type_for_data_model_field(field.get("type"), set())
        rendered.append(
            _render_pydantic_field_line(field_name, annotation, bool(field.get("required", False)))
        )
        seen_fields.add(field_name)
    return rendered


def _render_api_surface_endpoint_lines(method: dict, schemas: dict) -> list[str]:
    """Render a FastAPI-style endpoint scaffold from one deterministic lifecycle method."""
    operation_name = str(method.get("operation_name") or method.get("name") or "handle")
    request_schema = method.get("request_schema")
    response_schema = str(method.get("response_schema") or "dict[str, Any]")
    decorator_name = str(method.get("method", "GET")).lower()
    route_path = str(method.get("path", "/"))
    signature = _api_surface_endpoint_signature(method)
    response_lines = _api_surface_model_response_lines(method, schemas)
    rendered = [
        f'@router.{decorator_name}("{route_path}", response_model={response_schema})',
        f"def {operation_name}({signature}) -> {response_schema}:",
        f'    """{str(method.get("method", "GET"))} {route_path}."""',
    ]
    error_schema = method.get("error_schema")
    error_cases = method.get("error_cases", [])
    if isinstance(error_schema, str) and error_schema:
        if isinstance(error_cases, list) and error_cases:
            rendered.append(f"    # Errors use {error_schema}: {', '.join(str(case) for case in error_cases)}")
        else:
            rendered.append(f"    # Errors use {error_schema}.")
    rendered.extend(response_lines)
    return rendered


def _api_surface_endpoint_signature(method: dict) -> str:
    """Render the endpoint signature for a deterministic lifecycle operation."""
    operation_name = str(method.get("operation_name") or method.get("name") or "")
    request_schema = method.get("request_schema")
    if isinstance(request_schema, str) and request_schema:
        return f"payload: {request_schema}"
    if operation_name == "status":
        return "section_id: str"
    return "payload: dict[str, Any] | None = None"


def _api_surface_model_response_lines(method: dict, schemas: dict) -> list[str]:
    """Render a deterministic placeholder response model instance."""
    response_schema_name = method.get("response_schema")
    if not isinstance(response_schema_name, str):
        return ["    return {}"]
    schema_payload = schemas.get(response_schema_name)
    if not isinstance(schema_payload, dict):
        return [f"    return {response_schema_name}()"]
    fields = schema_payload.get("fields", [])
    if not isinstance(fields, list) or not fields:
        return [f"    return {response_schema_name}()"]

    lines = [f"    return {response_schema_name}("]
    for field in fields:
        if not isinstance(field, dict):
            continue
        field_name = _python_attribute_name(str(field.get("name", "")))
        if not field_name:
            continue
        lines.append(f"        {field_name}={_api_surface_placeholder_value(method, field)},")
    lines.append("    )")
    return lines


def _api_surface_placeholder_value(method: dict, field: dict) -> str:
    """Return one stable placeholder value for an api-surface response field."""
    field_name = _python_attribute_name(str(field.get("name", "")))
    field_type = str(field.get("type", "")).strip().lower()
    request_schema = method.get("request_schema")
    if field_name == "section_id":
        if isinstance(request_schema, str) and request_schema:
            return "payload.section_id"
        return "section_id"
    if field_name == "status":
        return '"pending"'
    if field_name == "next_action":
        return '"review"'
    if field_type in {"bool", "boolean"}:
        return "False"
    if field_type in {"int", "integer"}:
        return "0"
    if field_type in {"float", "number"}:
        return "0.0"
    return '""'


def _api_surface_method_signature(input_payload: object) -> str:
    """Render a typed Python signature from one api-surface input schema."""
    if not isinstance(input_payload, dict) or not input_payload:
        return "payload: dict[str, Any] | None = None"

    parts: list[str] = []
    for field_name in sorted(input_payload):
        attribute_name = _python_attribute_name(str(field_name))
        if not attribute_name:
            continue
        annotation = _python_type_for_api_surface_field(input_payload[field_name])
        parts.append(f"{attribute_name}: {annotation}")
    return ", ".join(parts) if parts else "payload: dict[str, Any] | None = None"


def _api_surface_response_lines(output_payload: object) -> list[str]:
    """Render a deterministic structured response body for one api-surface method."""
    if not isinstance(output_payload, dict) or not output_payload:
        return ["        return {}"]

    lines = ["        return {"]
    for field_name in sorted(output_payload):
        lines.append(f'            "{field_name}": None,')
    lines.append("        }")
    return lines


def _python_type_for_api_surface_field(value: object) -> str:
    """Map api-surface primitive field types into Python annotations."""
    if not isinstance(value, str):
        return "Any"
    normalized = value.strip().lower()
    primitive_map = {
        "boolean": "bool",
        "bool": "bool",
        "float": "float",
        "int": "int",
        "integer": "int",
        "number": "float",
        "str": "str",
        "string": "str",
    }
    if normalized in primitive_map:
        return primitive_map[normalized]
    return "Any"


def _python_type_for_data_model_field(value: object, known_entity_names: set[str]) -> str:
    """Map DGCE JSON field types into deterministic Python type annotations."""
    if not isinstance(value, str):
        return "Any"

    normalized = value.strip()
    if not normalized:
        return "Any"

    known_entity_lookup = {entity_name.lower(): entity_name for entity_name in known_entity_names}
    if normalized.lower() in known_entity_lookup:
        return known_entity_lookup[normalized.lower()]

    compact = re.sub(r"\s+", "", normalized)
    lowered_compact = compact.lower()
    primitive_map = {
        "any": "Any",
        "bool": "bool",
        "boolean": "bool",
        "datetime": "datetime",
        "dict": "dict[str, Any]",
        "dict[str,any]": "dict[str, Any]",
        "dict[string,any]": "dict[str, Any]",
        "float": "float",
        "int": "int",
        "integer": "int",
        "json": "dict[str, Any]",
        "number": "float",
        "object": "dict[str, Any]",
        "str": "str",
        "string": "str",
    }
    if lowered_compact in primitive_map:
        return primitive_map[lowered_compact]
    if lowered_compact in {"array", "list"}:
        return "list[Any]"

    list_match = re.match(r"^(?:array|list)\[(.+)\]$", compact, re.IGNORECASE)
    if list_match:
        nested = _python_type_for_data_model_field(list_match.group(1).strip(), known_entity_names)
        return f"list[{nested}]"
    if compact.endswith("[]"):
        nested = _python_type_for_data_model_field(compact[:-2].strip(), known_entity_names)
        return f"list[{nested}]"
    if lowered_compact in known_entity_lookup:
        return known_entity_lookup[lowered_compact]
    return compact if re.fullmatch(r"[A-Z][A-Za-z0-9]*", compact) else "Any"


def _field_annotation_with_enum_values(annotation: str, enum_values: object) -> str:
    """Prefer Literal[...] for deterministic enum-like field values when representable."""
    if not isinstance(enum_values, list) or not enum_values:
        return annotation

    literal_values: list[str] = []
    for value in enum_values:
        if isinstance(value, str):
            literal_values.append(repr(value))
            continue
        if isinstance(value, bool):
            literal_values.append("True" if value else "False")
            continue
        if isinstance(value, int) and not isinstance(value, bool):
            literal_values.append(str(value))
            continue
        return annotation

    deduped_values: list[str] = []
    for literal_value in literal_values:
        if literal_value not in deduped_values:
            deduped_values.append(literal_value)
    if not deduped_values:
        return annotation
    return f"Literal[{', '.join(deduped_values)}]"


def _python_attribute_name(value: str) -> str:
    """Normalize field and relationship names into deterministic Python attributes."""
    spaced = re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", value.strip())
    cleaned = re.sub(r"[^A-Za-z0-9_]+", "_", spaced).strip("_").lower()
    cleaned = re.sub(r"_+", "_", cleaned)
    if not cleaned:
        return ""
    if cleaned[0].isdigit():
        cleaned = f"field_{cleaned}"
    if keyword.iskeyword(cleaned):
        cleaned = f"{cleaned}_"
    return cleaned


def _fallback_data_model_class_name(stem: str, purpose: str) -> str:
    """Return a deterministic class name for data-model fallback files."""
    purpose_match = re.match(r"^Data model for ([A-Za-z0-9_]+)$", purpose.strip())
    if purpose_match:
        return purpose_match.group(1)
    if "_" in stem or "-" in stem:
        return _class_name(stem)

    lowered_stem = stem.strip().lower()
    compound_tokens = _split_known_compound_token(lowered_stem)
    if compound_tokens:
        return "".join(token.capitalize() for token in compound_tokens)
    return _class_name(stem)


def _split_known_compound_token(value: str) -> list[str]:
    """Best-effort split for lowercase compound DGCE identifiers such as sectioninput."""
    vocabulary = sorted(
        {
            "alignment",
            "approval",
            "artifact",
            "content",
            "data",
            "datetime",
            "entity",
            "execution",
            "field",
            "fingerprint",
            "gate",
            "input",
            "item",
            "metadata",
            "model",
            "output",
            "payload",
            "preflight",
            "preview",
            "record",
            "review",
            "section",
            "stamp",
            "status",
        },
        key=len,
        reverse=True,
    )
    tokens: list[str] = []
    index = 0
    while index < len(value):
        match = next((word for word in vocabulary if value.startswith(word, index)), None)
        if match is None:
            return []
        tokens.append(match)
        index += len(match)
    return tokens


def _expected_target_class_name(value: str) -> str:
    """Return a readable class name for expected-target bootstrap scaffolds."""
    normalized = value.replace("-", "_").strip("_")
    if not normalized:
        return "GeneratedStub"

    special_cases = {
        "rsobservation": "RSObservation",
    }
    if normalized in special_cases:
        return special_cases[normalized]

    return "".join(_expected_target_class_token(part) for part in normalized.split("_") if part) or "GeneratedStub"


def _expected_target_class_token(value: str) -> str:
    """Normalize one snake-case token into a class-name token."""
    if value.lower() == "rso":
        return "RSO"
    return value[:1].upper() + value[1:]


def _infer_component_method_name(purpose: str) -> str:
    """Infer a minimal component method name from a human purpose string."""
    lowered = purpose.lower()
    if "classif" in lowered:
        return "classify"
    if "normaliz" in lowered:
        return "normalize"
    if "validat" in lowered:
        return "validate"
    if "score" in lowered:
        return "score"
    if "review" in lowered:
        return "review"
    if "route" in lowered:
        return "route"
    if "ingest" in lowered:
        return "ingest"
    if "process" in lowered:
        return "process"
    return "execute"


def _infer_api_function_name(purpose: str, stem: str) -> str:
    """Infer a minimal API function name from purpose text or the module stem."""
    lowered = purpose.lower()
    if "ingest" in lowered:
        return "ingest_observation"
    if "review" in lowered:
        return "review_anomaly"
    if "status" in lowered:
        return "get_status"
    if "health" in lowered:
        return "get_health"
    return f"handle_{stem.replace('-', '_')}"


def _infer_test_name(stem: str) -> str:
    """Infer a deterministic pytest-style placeholder test name."""
    normalized = stem.replace("-", "_")
    if normalized.startswith("test_"):
        return normalized
    return f"test_{normalized}_placeholder"


def _infer_model_fields(class_name: str, requirements: list[str]) -> list[tuple[str, str, str]]:
    """Infer deterministic typed model fields from requirements."""
    known_fields = [
        ("object_id", "str", '""'),
        ("timestamp", "str", '""'),
        ("position_eci", "tuple[float, float, float]", "(0.0, 0.0, 0.0)"),
        ("velocity_eci", "tuple[float, float, float]", "(0.0, 0.0, 0.0)"),
        ("sensor_source", "str", '""'),
        ("data_quality", "float", "0.0"),
        ("anomaly_id", "str", '""'),
        ("observation_id", "str", '""'),
        ("anomaly_type", "str", '""'),
        ("deviation_score", "float", "0.0"),
        ("confidence", "float", "0.0"),
        ("status", "str", '"pending"'),
        ("guardrail_cleared", "bool", "False"),
        ("operator_review_required", "bool", "True"),
        ("reason_codes", "list[str]", "None"),
        ("reasoning", "str", '""'),
    ]
    relevant_requirements = [
        requirement
        for requirement in requirements
        if class_name.lower() in requirement.lower()
    ]
    lowered_requirements = " ".join(requirement.lower() for requirement in relevant_requirements)
    fields = [field for field in known_fields if field[0].lower() in lowered_requirements]

    if class_name == "RSObservation" and not fields:
        default_names = {"object_id", "timestamp"}
        fields = [field for field in known_fields if field[0] in default_names]

    if class_name == "AnomalyRecord":
        required_names = {"status"} if _requirements_mention_status(relevant_requirements) else set()
        if required_names:
            existing_names = {field[0] for field in fields}
            fields.extend(field for field in known_fields if field[0] in required_names - existing_names)

    if not fields:
        return [("placeholder_id", "str", '""')]

    deduped: list[tuple[str, str, str]] = []
    seen: set[str] = set()
    for field in fields:
        if field[0] in seen:
            continue
        deduped.append(field)
        seen.add(field[0])
    return deduped


def _render_model_fields(fields: list[tuple[str, str, str]]) -> list[str]:
    """Render typed field lines for a fallback model scaffold."""
    if len(fields) == 1 and fields[0][0] == "placeholder_id":
        return [
            "    # TODO: replace placeholder fields with typed model attributes.",
            '    placeholder_id: str = ""',
        ]

    rendered = ["    # Typed fields inferred from expected-target requirements."]
    for name, annotation, default in fields:
        if annotation.startswith("list[") and default == "None":
            rendered.append(f"    {name}: {annotation} | None = None")
        else:
            rendered.append(f"    {name}: {annotation} = {default}")
    if any(name == "status" for name, _, _ in fields):
        rendered.append("    # Allowed status values should be driven by the section requirements.")
    return rendered


def _render_model_validate_method(fields: list[tuple[str, str, str]], requirements: list[str]) -> list[str]:
    """Render a minimal validate() implementation for fallback model scaffolds."""
    basic_checks = []
    field_names = {name for name, _, _ in fields}
    if "object_id" in field_names:
        basic_checks.append('        if not self.object_id:\n            raise ValueError("object_id is required")')
    if "timestamp" in field_names:
        basic_checks.append('        if not self.timestamp:\n            raise ValueError("timestamp is required")')
    if "status" in field_names and _requirements_mention_status(requirements):
        basic_checks.append(
            '        if self.status not in {"pending", "approved", "rejected"}:\n'
            '            raise ValueError("status must be a supported workflow value")'
        )
    if not basic_checks and not _requirements_mention_validate(requirements):
        return [
            "    def validate(self) -> None:",
            '        """Validate the current model state."""',
            "        pass",
        ]

    lines = [
        "    def validate(self) -> None:",
        '        """Validate the current model state."""',
    ]
    for block in basic_checks:
        lines.extend(block.splitlines())
    if not basic_checks:
        lines.append("        pass")
    return lines


def _render_component_method_lines(class_name: str, purpose: str, requirements: list[str]) -> list[str]:
    """Render a minimal expected-target component method scaffold."""
    if class_name == "GuardrailGateway":
        return [
            "    def enforce_policy(self, anomaly_record: dict) -> bool:",
            '        """Enforce Guardrail policy before escalation or outbound action."""',
            "        return True",
        ]

    if class_name == "ObservationNormalizer":
        return [
            "    def normalize_observation(self, raw_data: dict) -> dict:",
            '        """Normalize raw orbital observation data into a standard structure."""',
            "        return dict(raw_data)",
        ]

    if class_name == "OrbitPropagator":
        return [
            "    def propagate_orbit(self, normalized_observation: dict, time_step: float) -> dict:",
            '        """Estimate expected motion for a normalized observation."""',
            "        return {",
            '            "expected_position_eci": normalized_observation.get("position_eci", (0.0, 0.0, 0.0)),',
            '            "expected_velocity_eci": normalized_observation.get("velocity_eci", (0.0, 0.0, 0.0)),',
            '            "time_step": time_step,',
            "        }",
        ]

    if class_name == "DeviationScorer":
        return [
            "    def score_deviation(self, observed_state: dict, expected_state: dict) -> float:",
            '        """Compute a deviation score between observed and expected state."""',
            "        # Placeholder: simple magnitude difference proxy",
            "        return 0.0",
        ]

    if class_name == "ReviewQueueManager":
        return [
            "    def submit_for_review(self, anomaly_record: dict) -> dict:",
            '        """Queue an anomaly record for operator review."""',
            "        return {",
            '            "anomaly_id": anomaly_record.get("anomaly_id", ""),',
            '            "queued": True,',
            "        }",
            "",
            "    def update_review_status(self, anomaly_id: str, status: str) -> dict:",
            '        """Update the review status for an anomaly record."""',
            "        return {",
            '            "anomaly_id": anomaly_id,',
            '            "status": status,',
            "        }",
        ]

    if class_name == "AnomalyClassifier":
        return [
            "    def classify(self, observation: dict, expected_state: dict) -> dict:",
            '        """Classify an observation against an expected state; anomaly_type should be one of RPO, maneuver, conjunction, or unknown."""',
            '        return {"anomaly_type": "unknown", "confidence": 0.0}',
        ]

    if _requirements_mention_classify(requirements):
        return [
            "    def classify(self, observation: dict, expected_state: dict) -> dict:",
            '        """Classify an observation against an expected state; anomaly_type should be one of RPO, maneuver, conjunction, or unknown."""',
            '        return {"anomaly_type": "unknown", "confidence": 0.0}',
        ]

    method_name = _infer_component_method_name(purpose)
    return [
        f"    def {method_name}(self, payload: dict) -> dict:",
        f'        """Placeholder for {method_name.replace("_", " ")} behavior."""',
        "        raise NotImplementedError",
    ]


def _requirements_mention_validate(requirements: list[str]) -> bool:
    """Return True when requirements explicitly call for validate()."""
    lowered = " ".join(requirement.lower() for requirement in requirements)
    return "validate()" in lowered or "must include validate" in lowered


def _requirements_mention_status(requirements: list[str]) -> bool:
    """Return True when requirements mention status workflow expectations."""
    lowered = " ".join(requirement.lower() for requirement in requirements)
    return "status" in lowered


def _requirements_mention_classify(requirements: list[str]) -> bool:
    """Return True when requirements mention classify()."""
    lowered = " ".join(requirement.lower() for requirement in requirements)
    return "classify(" in lowered or "must expose classify" in lowered
