# Generated by Aether
# Path: src/api/ingest.py
# Purpose: Provide observation ingestion entry points for anomaly detection
# Source: expected_targets

"""Public anomaly ingestion entrypoint for Defiant Sky.

Accepted input:
- `dict` payloads with observation fields such as `object_id`, `timestamp`,
  `position_eci`, `velocity_eci`, `sensor_source`, and `data_quality`
- `RSObservation` instances

Returned output:
- `anomaly_type`
- `confidence`
- `deviation_score`
- additive guardrail, review, and advisory metadata
"""

from dataclasses import asdict

try:
    from aether_core.itera.advisory import build_advisory
except ModuleNotFoundError:
    def build_advisory(execution_outcome: dict, section_id: str) -> dict | None:
        """Local fallback for advisory import during isolated Defiant Sky test runs."""
        validation = execution_outcome.get("validation_summary", {})
        status = execution_outcome.get("status")
        execution = execution_outcome.get("execution_summary", {})

        if validation.get("ok") is False:
            explanation = ["validation_failed"]
            if validation.get("missing_keys"):
                explanation.append("missing_required_keys")
            return {
                "type": "policy_adjustment",
                "summary": f"Review schema contract handling for {section_id}",
                "explanation": explanation,
            }

        if status == "partial":
            explanation = ["partial_run"]
            if execution.get("skipped_modify_count", 0) > 0:
                explanation.append("skipped_modify")
            if execution.get("skipped_ignore_count", 0) > 0:
                explanation.append("skipped_ignore")
            return {
                "type": "process_adjustment",
                "summary": f"Review incremental skip behavior for {section_id}",
                "explanation": explanation,
            }

        if status == "error":
            return {
                "type": "process_adjustment",
                "summary": f"Review failed DGCE run flow for {section_id}",
                "explanation": ["execution_error"],
            }

        return None
from components.anomaly_classifier import AnomalyClassifier
from components.deviation_scorer import DeviationScorer
from components.guardrail_gateway import GuardrailGateway
from components.observation_normalizer import ObservationNormalizer
from components.orbit_propagator import OrbitPropagator
from components.review_queue_manager import ReviewQueueManager
from models.anomaly_record import AnomalyRecord
from models.rsobservation import RSObservation

LOW_CONFIDENCE_THRESHOLD = 0.5
DEGRADED_MODE_THRESHOLD = 0.6


def _as_observation(payload: dict | RSObservation) -> RSObservation:
    """Normalize caller input to an RSObservation instance."""
    if isinstance(payload, RSObservation):
        return payload
    if not isinstance(payload, dict):
        raise TypeError("payload must be a dict or RSObservation")

    return RSObservation(
        object_id=str(payload.get("object_id", "")),
        timestamp=str(payload.get("timestamp", "")),
        position_eci=tuple(payload.get("position_eci", (0.0, 0.0, 0.0))),
        velocity_eci=tuple(payload.get("velocity_eci", (0.0, 0.0, 0.0))),
        sensor_source=str(payload.get("sensor_source", "")),
        data_quality=float(payload.get("data_quality", 0.0)),
    )


def _serialize_observation(observation: RSObservation) -> dict:
    """Serialize an observation dataclass for component-facing dict APIs."""
    return asdict(observation)


def _as_anomaly_record_response(anomaly_record: AnomalyRecord, review_ticket: dict | None) -> dict:
    """Return the stable outward response shape for ingest callers."""
    return {
        "anomaly_type": anomaly_record.anomaly_type,
        "confidence": anomaly_record.confidence,
        "deviation_score": anomaly_record.deviation_score,
        "guardrail_cleared": anomaly_record.guardrail_cleared,
        "review_required": anomaly_record.operator_review_required,
        "escalation_blocked": anomaly_record.operator_review_required and review_ticket is None,
        "review_ticket": review_ticket,
    }


def _build_itera_advisory(anomaly_record: AnomalyRecord, *, review_ticket: dict | None) -> dict:
    """Build additive advisory metadata for the anomaly decision context."""
    execution_outcome = {
        "status": "partial" if anomaly_record.operator_review_required and review_ticket is None else "success",
        "validation_summary": {
            "ok": True,
            "missing_keys": [],
        },
        "execution_summary": {
            "skipped_modify_count": 1 if anomaly_record.operator_review_required and review_ticket is None else 0,
            "skipped_ignore_count": 0,
        },
    }
    advisory = build_advisory(execution_outcome, "defiant-sky-anomaly-detection-core")
    return {
        "advisory_present": advisory is not None,
        "advisory_type": advisory.get("type") if advisory else None,
        "advisory_summary": advisory.get("summary") if advisory else None,
        "advisory_context_key": anomaly_record.anomaly_id,
    }


def _safe_itera_advisory(anomaly_record: AnomalyRecord, *, review_ticket: dict | None) -> dict:
    """Return advisory metadata without affecting primary control flow."""
    try:
        return _build_itera_advisory(anomaly_record, review_ticket=review_ticket)
    except Exception:
        return {
            "advisory_present": False,
            "advisory_type": None,
            "advisory_summary": None,
            "advisory_context_key": anomaly_record.anomaly_id,
        }


def _is_degraded_mode(payload: dict | RSObservation) -> bool:
    """Return True when the caller indicates degraded sensor conditions."""
    if isinstance(payload, dict):
        if bool(payload.get("degraded_mode", False)):
            return True
        sensor_availability = payload.get("sensor_availability")
        if sensor_availability is not None:
            return float(sensor_availability) < DEGRADED_MODE_THRESHOLD
    return False


def ingest_observation(payload: dict | RSObservation) -> dict:
    """
    Run the public anomaly-detection ingest pipeline.

    The function validates caller input, executes the deterministic anomaly
    pipeline, applies guardrail-gated escalation logic, and returns a stable
    dict response containing anomaly, review, and advisory fields.
    """

    observation = _as_observation(payload)
    observation.validate()

    normalizer = ObservationNormalizer()
    propagator = OrbitPropagator()
    scorer = DeviationScorer()
    classifier = AnomalyClassifier()
    guardrail = GuardrailGateway()
    review_queue = ReviewQueueManager()

    normalized_payload = normalizer.normalize_observation(_serialize_observation(observation))
    normalized_observation = _as_observation(normalized_payload)
    normalized_observation.validate()

    normalized_state = _serialize_observation(normalized_observation)
    expected_state = propagator.propagate_orbit(normalized_state, time_step=0.0)
    deviation_score = scorer.score_deviation(normalized_state, expected_state)
    classification = classifier.classify(normalized_state, expected_state)

    anomaly_record = AnomalyRecord(
        object_id=normalized_observation.object_id,
        anomaly_id=f"{normalized_observation.object_id}:{normalized_observation.timestamp}",
        observation_id=normalized_observation.timestamp,
        anomaly_type=str(classification.get("anomaly_type", "unknown")),
        deviation_score=deviation_score,
        confidence=float(classification.get("confidence", 0.0)),
        status="pending",
        reason_codes=[],
        reasoning="Generated by the anomaly detection ingest pipeline.",
    )
    anomaly_record.validate()

    anomaly_record.guardrail_cleared = guardrail.enforce_policy(asdict(anomaly_record))
    anomaly_record.operator_review_required = (
        anomaly_record.anomaly_type != "unknown" or anomaly_record.confidence < 1.0
    )
    anomaly_record.validate()

    degraded_mode_violation = _is_degraded_mode(payload)
    low_confidence_violation = anomaly_record.confidence < LOW_CONFIDENCE_THRESHOLD
    escalation_allowed = (
        anomaly_record.operator_review_required
        and anomaly_record.guardrail_cleared
        and not degraded_mode_violation
        and not low_confidence_violation
    )

    review_ticket = None
    if escalation_allowed:
        review_ticket = review_queue.submit_for_review(asdict(anomaly_record))

    response = _as_anomaly_record_response(anomaly_record, review_ticket)
    response.update(_safe_itera_advisory(anomaly_record, review_ticket=review_ticket))
    return response
