# Generated by Aether
# Path: src/api/review.py
# Purpose: Provide review and escalation entry points for anomaly records
# Source: expected_targets

"""Public anomaly review entrypoint for Defiant Sky."""

from components.audit_trail_writer import AuditTrailWriter
from components.review_queue_manager import ReviewQueueManager
from models.anomaly_record import AnomalyRecord


def review_anomaly(anomaly_record: dict, status: str) -> dict:
    """
    Review an anomaly record with an approved or rejected terminal status.
    """

    if status not in {"approved", "rejected"}:
        raise ValueError("status must be approved or rejected")

    record = AnomalyRecord(
        object_id=str(anomaly_record.get("object_id", "")),
        anomaly_id=str(anomaly_record.get("anomaly_id", "")),
        observation_id=str(anomaly_record.get("observation_id", "")),
        anomaly_type=str(anomaly_record.get("anomaly_type", "")),
        deviation_score=float(anomaly_record.get("deviation_score", 0.0)),
        confidence=float(anomaly_record.get("confidence", 0.0)),
        status=str(anomaly_record.get("status", "pending")),
        guardrail_cleared=bool(anomaly_record.get("guardrail_cleared", False)),
        operator_review_required=bool(anomaly_record.get("operator_review_required", True)),
        reason_codes=list(anomaly_record.get("reason_codes", []) or []),
        reasoning=str(anomaly_record.get("reasoning", "")),
    )
    if record.object_id:
        record.validate()
    record.mark_reviewed(status)
    if record.object_id:
        record.validate()

    queue_manager = ReviewQueueManager()
    queue_update = queue_manager.update_review_status(record.anomaly_id, record.status)
    audit_writer = AuditTrailWriter()

    updated_record = dict(anomaly_record)
    updated_record["status"] = record.status
    audit_writer.write_audit_event(
        {
            "anomaly_id": record.anomaly_id,
            "event_type": "review_status_updated",
            "status": record.status,
            "updated_record": updated_record,
        }
    )

    return {
        "anomaly_id": queue_update["anomaly_id"],
        "status": queue_update["status"],
        "updated_record": updated_record,
    }
