# Generated by Aether
# Path: models/alignmentrecord.py
# Purpose: Data model for AlignmentRecord
# Source: data_model

"""Pydantic model for AlignmentRecord."""

from __future__ import annotations

from pydantic import BaseModel

class AlignmentRecord(BaseModel):
    """Implementation-ready DGCE model for AlignmentRecord."""

    alignment_fingerprint: str | None = None
    section_id: str
