# Generated by Aether
# Path: models/executionstamp.py
# Purpose: Data model for ExecutionStamp
# Source: data_model

"""Pydantic model for ExecutionStamp."""

from __future__ import annotations

from pydantic import BaseModel

class ExecutionStamp(BaseModel):
    """Implementation-ready DGCE model for ExecutionStamp."""

    artifact_fingerprint: str | None = None
    execution_timestamp: str
    run_outcome_class: str | None = None
    section_id: str
    output: Output | None = None
