# Generated by Aether
# Path: models/executiongate.py
# Purpose: Data model for ExecutionGate
# Source: data_model

"""Pydantic model for ExecutionGate."""

from __future__ import annotations

from pydantic import BaseModel

class ExecutionGate(BaseModel):
    """Implementation-ready DGCE model for ExecutionGate."""

    execution_fingerprint: str | None = None
    section_id: str
