# Generated by Aether
# Path: models/executionstamp.py
# Purpose: Data model for ExecutionStamp
# Source: data_model

"""Pydantic model for ExecutionStamp."""

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel

class ExecutionStamp(BaseModel):
    """Implementation-ready DGCE model for ExecutionStamp."""

    execution_outcome: Literal['failure', 'success'] | None = None
    section_id: str
