# Generated by Aether
# Path: models/output.py
# Purpose: Data model for Output
# Source: data_model

"""Pydantic model for Output."""

from __future__ import annotations

from pydantic import BaseModel

class Output(BaseModel):
    """Implementation-ready DGCE model for Output."""

    artifact_fingerprint: str | None = None
    section_id: str
