# Generated by Aether
# Path: models/preflightrecord.py
# Purpose: Data model for PreflightRecord
# Source: data_model

"""Pydantic model for PreflightRecord."""

from __future__ import annotations

from pydantic import BaseModel

class PreflightRecord(BaseModel):
    """Implementation-ready DGCE model for PreflightRecord."""

    preflight_fingerprint: str | None = None
    section_id: str
