# Generated by Aether
# Path: models/reviewartifact.py
# Purpose: Data model for ReviewArtifact
# Source: data_model

"""Pydantic model for ReviewArtifact."""

from __future__ import annotations

from pydantic import BaseModel

class ReviewArtifact(BaseModel):
    """Implementation-ready DGCE model for ReviewArtifact."""

    artifact_fingerprint: str | None = None
    section_id: str
    approval_artifact: ApprovalArtifact | None = None
