# Generated by Aether
# Path: models/sectioninput.py
# Purpose: Data model for SectionInput
# Source: data_model

"""Pydantic model for SectionInput."""

from __future__ import annotations

from typing import Any

from pydantic import BaseModel

class SectionInput(BaseModel):
    """Implementation-ready DGCE model for SectionInput."""

    content: dict[str, Any] | None = None
    input_fingerprint: str | None = None
    section_id: str
    preview_artifact: PreviewArtifact | None = None
