# Generated by Aether
# Path: models/sectioninput.py
# Purpose: Data model for SectionInput
# Source: data_model

"""Pydantic model for SectionInput."""

from __future__ import annotations

from pydantic import BaseModel

class SectionInput(BaseModel):
    """Implementation-ready DGCE model for SectionInput."""

    input_fingerprint: str | None = None
    section_id: str
