# Generated by Aether
# Path: src/models/anomaly_record.py
# Purpose: Define the AnomalyRecord model for scored and classified anomalies
# Source: expected_targets

from dataclasses import dataclass

"""Fallback model scaffold for AnomalyRecord."""

@dataclass
class AnomalyRecord:
    """Define the AnomalyRecord model for scored and classified anomalies"""

    # Typed fields inferred from expected-target requirements.
    object_id: str = ""
    anomaly_id: str = ""
    observation_id: str = ""
    anomaly_type: str = ""
    deviation_score: float = 0.0
    confidence: float = 0.0
    status: str = "pending"
    guardrail_cleared: bool = False
    operator_review_required: bool = True
    reason_codes: list[str] | None = None
    reasoning: str = ""
    # Allowed status values should be driven by the section requirements.

    def validate(self) -> None:
        """Validate the current model state."""
        if not self.object_id:
            raise ValueError("object_id is required")
        if self.status not in {"pending", "approved", "rejected"}:
            raise ValueError("status must be a supported workflow value")

    # Allowed status values: pending, approved, rejected
    def mark_reviewed(self, status: str) -> None:
        """Update the record status after operator review."""
        if status not in {"approved", "rejected"}:
            raise ValueError("status must be approved or rejected")
        self.status = status
