# Generated by Aether
# Path: src/models/rsobservation.py
# Purpose: Define the RSObservation data model for normalized orbital observations
# Source: expected_targets

from dataclasses import dataclass

"""Fallback model scaffold for RSObservation."""

@dataclass
class RSObservation:
    """Define the RSObservation data model for normalized orbital observations"""

    # Typed fields inferred from expected-target requirements.
    object_id: str = ""
    timestamp: str = ""
    position_eci: tuple[float, float, float] = (0.0, 0.0, 0.0)
    velocity_eci: tuple[float, float, float] = (0.0, 0.0, 0.0)
    sensor_source: str = ""
    data_quality: float = 0.0

    def validate(self) -> None:
        """Validate the current model state."""
        if not self.object_id:
            raise ValueError("object_id is required")
        if not self.timestamp:
            raise ValueError("timestamp is required")
