# Generated by Aether
# Path: api/datamodelinterface.py
# Purpose: API interface for DataModelInterface
# Source: api_surface

"""API scaffold for API interface for DataModelInterface."""

class Datamodelinterface:
    """Defines the api interface for datamodelinterface."""

    pass
