# Generated by Aether
# Path: api/executiongateinterface.py
# Purpose: API interface for ExecutionGateInterface
# Source: api_surface

"""API scaffold for API interface for ExecutionGateInterface."""

class Executiongateinterface:
    """Defines the api interface for executiongateinterface."""

    pass
