# Generated by Aether
# Path: api/reviewartifactinterface.py
# Purpose: API interface for ReviewArtifactInterface
# Source: api_surface

"""API scaffold for API interface for ReviewArtifactInterface."""

class Reviewartifactinterface:
    """Defines the api interface for reviewartifactinterface."""

    pass
