# Generated by Aether
# Path: api/reviewartifact.py
# Purpose: API interface for ReviewArtifact
# Source: api_surface

"""API scaffold for API interface for ReviewArtifact."""

class Reviewartifact:
    """Defines the api interface for reviewartifact."""

    pass
