# Generated by Aether
# Path: api/sectioninputinterface.py
# Purpose: API interface for SectionInputInterface
# Source: api_surface

"""API scaffold for API interface for SectionInputInterface."""

class Sectioninputinterface:
    """Defines the api interface for sectioninputinterface."""

    pass
